import type { Metadata } from "next";
import { Open_Sans, Poppins } from "next/font/google";
import "./globals.css";

import Header from "@/components/header";
import ThemeProvider from "@/components/ui/theme-provider";
// import Cursor from "@/components/ui/cursor";

const openSans = Open_Sans({
    subsets: ["latin"],
    variable: "--font-open-sans",
    preload: true,
    weight: ["300", "400", "500", "600", "700", "800"],
});

const poppins = Poppins({
    subsets: ["latin"],
    variable: "--font-poppins",
    preload: true,
    weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

interface RootLayoutProps {
    children: React.ReactNode;
}

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
    return (
        <html lang="en">
            <body
                className={`antialiased ${openSans.variable} ${poppins.variable} dark:bg-black`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    // disableTransitionOnChange
                >
                    {/* <Cursor /> */}
                    <Header />
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
